### ISSUE TITLE
Help run scene

### ISSUE THREAD

**Issue by givanildo** [cybermaggedon/pyvera#8]
First of all, I wanted to thank you for your amazing work !!! 
but ,...
How can i do to run a specific scene
ex.:

cooler = ve.get_scene("Cooler Water")
....
cooler.run()

I tried several ways and i can't  do it run
Please I need some help

////////////////////////////////////////////////

scenes = ve.get_scenes()
for i in scenes:
    if i.name == "Hot water":
        i.run() ////////"

**Comment by cybermaggedon** [comment]
Sorry for missing this!!!  Yeh you have the answer in your post...

```
#!/usr/bin/env python3

import sys
import vera
ve = vera.connect("LOCAL.cfg")

scenes = ve.get_scenes()

for scene in scenes:
    if scene.name == "Heating water on":
        print("Invoke")
        scene.run()
```
